{ question: "¿Qué es la diabetes?", options: ["Enfermedad crónica que afecta el metabolismo de la glucosa", "Una infección", "Un tipo de cáncer", "Una alergia"], answer: 0 },
    { question: "¿Cuáles son los tipos principales de diabetes?", options: ["Tipo 1 y Tipo 2", "Tipo A y Tipo B", "Diabetes gestacional y prediabetes", "Solo Tipo 1"], answer: 0 },
    { question: "¿Qué hormona regula la glucosa en sangre?", options: ["Insulina", "Adrenalina", "Cortisol", "Glucagón"], answer: 0 },
    { question: "¿Qué síntomas son comunes en diabetes?", options: ["Sed excesiva y micción frecuente", "Dolor de cabeza", "Fiebre", "Dolor abdominal"], answer: 0 },
    { question: "¿Cómo se diagnostica la diabetes?", options: ["Medición de glucosa en sangre", "Radiografía", "Ecografía", "Análisis de orina"], answer: 0 },
    { question: "¿Qué complicaciones puede causar la diabetes?", options: ["Problemas renales y visión", "Dolor de cabeza", "Resfriados frecuentes", "Pérdida de peso"], answer: 0 },
    { question: "¿Qué tipo de dieta se recomienda?", options: ["Baja en azúcares y carbohidratos simples", "Alta en grasas", "Solo líquidos", "Solo proteínas"], answer: 0 },
    { question: "¿Qué es la hipoglucemia?", options: ["Bajo nivel de azúcar en sangre", "Alto nivel de azúcar en sangre", "Falta de insulina", "Exceso de glucosa"], answer: 0 },
    { question: "¿Qué tipo de ejercicio es recomendado?", options: ["Ejercicio moderado y regular", "Ejercicio intenso", "Ninguno", "Solo yoga"], answer: 0 },
    { question: "¿Se puede prevenir la diabetes tipo 2?", options: ["Sí, con hábitos saludables", "No", "Solo con medicamentos", "Solo con cirugía"], answer: 0 },
    { question: "¿Qué es la insulina?", options: ["Hormona que regula la glucosa", "Una enzima", "Un anticuerpo", "Un neurotransmisor"], answer: 0 },
    { question: "¿Cuál es la causa principal de diabetes tipo 1?", options: ["Destrucción autoinmune de células beta", "Dieta alta en azúcar", "Falta de ejercicio", "Obesidad"], answer: 0 },
    { question: "¿Qué es la diabetes gestacional?", options: ["Diabetes durante el embarazo", "Diabetes en niños", "Diabetes en ancianos", "Diabetes temporal"], answer: 0 },
    { question: "¿Qué controles son importantes en diabetes?", options: ["Monitoreo de glucosa y HbA1c", "Radiografías", "Ecografías", "Electrocardiogramas"], answer: 0 },
    { question: "¿Qué es la neuropatía diabética?", options: ["Daño a los nervios por diabetes", "Dolor de cabeza", "Problemas pulmonares", "Inflamación de la piel"], answer: 0 },
    { question: "¿Qué tipo de medicamentos se usan?", options: ["Insulina y antidiabéticos orales", "Antibióticos", "Antiinflamatorios", "Analgesicos"], answer: 0 },
    { question: "¿Qué es la retinopatía diabética?", options: ["Daño a los vasos sanguíneos del ojo", "Dolor ocular", "Infección ocular", "Pérdida de audición"], answer: 0 },
    { question: "¿Cuál es un síntoma de hiperglucemia?", options: ["Sed intensa", "Dolor de cabeza", "Fiebre", "Dolor de estómago"], answer: 0 },
    { question: "¿Se puede vivir bien con diabetes?", options: ["Sí, con control adecuado", "No", "Solo con insulina", "Solo con dieta"], answer: 0 },
    { question: "¿Qué es la glucosa?", options: ["Azúcar en sangre", "Proteína", "Grasa", "Mineral"], answer: 0 }
  ]




const triviaData = {
  "Frases por terminar": [
    { question: "A quien madruga...", options: ["Dios lo ayuda", "Se le caen las pestañas", "Le da más sueño", "Le falta café"], answer: 0 },
    { question: "Más vale pájaro en mano...", options: ["Que ciento volando", "Que dos en el nido", "Que uno sin alas", "Que mil ideas"], answer: 0 },
    { question: "El que mucho abarca...", options: ["Poco aprieta", "Mucho pierde", "Poco duerme", "Nada gana"], answer: 0 },
    { question: "No hay mal...", options: ["Que por bien no venga", "Que dure cien años", "Que se resista", "Que no duela"], answer: 0 },
    { question: "Cría cuervos...", options: ["Y te sacarán los ojos", "Y tendrás compañía", "Y volarán contigo", "Y comerán queso"], answer: 0 },
    { question: "A caballo regalado...", options: ["No se le mira el diente", "Hay que decir gracias", "Se le monta", "Se le da avena"], answer: 0 },
    { question: "Cuando el río suena...", options: ["Agua lleva", "Es por algo", "Corre el pez", "Hay tormenta"], answer: 0 },
    { question: "Más vale tarde...", options: ["Que nunca", "Que temprano", "Que lento", "Que malo"], answer: 0 },
    { question: "Al mal tiempo...", options: ["Buena cara", "Un paraguas", "Malas noticias", "No salgas"], answer: 0 },
    { question: "Ojos que no ven...", options: ["Corazón que no siente", "No ven la realidad", "Mirada perdida", "No lloran"], answer: 0 },
    { question: "Camarón que se duerme...", options: ["Se lo lleva la corriente", "Sueña con agua", "No pesca", "Se despierta tarde"], answer: 0 },
    { question: "Dime con quién andas...", options: ["Y te diré quién eres", "Y caminamos juntos", "Y sabré tu destino", "Y veré tu estilo"], answer: 0 },
    { question: "Perro que ladra...", options: ["No muerde", "Tiene hambre", "Se hace notar", "Molesta"], answer: 0 },
    { question: "No dejes para mañana...", options: ["Lo que puedas hacer hoy", "Lo que no quieres hacer", "El café", "La siesta"], answer: 0 },
    { question: "En casa de herrero...", options: ["Cuchillo de palo", "Mucho hierro", "No hay pan", "Herraduras viejas"], answer: 0 },
    { question: "A palabras necias...", options: ["Oídos sordos", "Respuestas sabias", "Silencio", "Palabras sabias"], answer: 0 },
    { question: "Haz bien...", options: ["Y no mires a quién", "Y duerme tranquilo", "Y te irá mejor", "Y repítelo"], answer: 0 },
    { question: "Cuando el gato no está...", options: ["Los ratones bailan", "La casa está sola", "Todo se pierde", "El queso desaparece"], answer: 0 },
    { question: "El hábito...", options: ["No hace al monje", "Esconde el alma", "Cambia todo", "Hace costumbre"], answer: 0 },
    { question: "Más sabe el diablo por viejo...", options: ["Que por diablo", "Que por sabio", "Que por astuto", "Que por malo"], answer: 0 },
    { question: "Del dicho al hecho...", options: ["Hay mucho trecho", "Todo cambia", "No hay distancia", "Va el camino"], answer: 0 },
    { question: "Hierba mala...", options: ["Nunca muere", "Crece rápido", "Duele más", "Se riega sola"], answer: 0 },
    { question: "El que ríe último...", options: ["Ríe mejor", "No entendió el chiste", "Ríe solo", "Ya no ríe"], answer: 0 },
    { question: "Donde hubo fuego...", options: ["Cenizas quedan", "Hay humo", "Hubo calor", "No queda nada"], answer: 0 },
    { question: "Cada loco...", options: ["Con su tema", "Con su locura", "Con su mundo", "Con su espejo"], answer: 0 },
    { question: "No hay peor ciego...", options: ["Que el que no quiere ver", "Que el que niega la luz", "Que el que olvida", "Que el que mira sin ver"], answer: 0 },
    { question: "De tal palo...", options: ["Tal astilla", "Tal sombra", "Tal corte", "Tal árbol"], answer: 0 },
    { question: "A mal paso...", options: ["Dar prisa", "Cambiar camino", "Mirar atrás", "Correr más"], answer: 0 },
    { question: "En boca cerrada...", options: ["No entran moscas", "No hay errores", "Hay silencio", "No hay chismes"], answer: 0 },
    { question: "Aunque la mona se vista de seda...", options: ["Mona se queda", "No es princesa", "No es reina", "Lujo no cambia"], answer: 0 },
    { question: "Agua que no has de beber...", options: ["Déjala correr", "No la toques", "Es de otro", "Se evaporará"], answer: 0 },
    { question: "No todo lo que brilla...", options: ["Es oro", "Es real", "Es bonito", "Es bueno"], answer: 0 },
    { question: "Barriga llena...", options: ["Corazón contento", "Cabeza dormida", "Cuerpo feliz", "Sueño asegurado"], answer: 0 },
    { question: "Quien calla...", options: ["Otorga", "No escucha", "Se pierde", "Sufre"], answer: 0 },
    { question: "Más vale prevenir...", options: ["Que curar", "Que lamentar", "Que correr", "Que olvidar"], answer: 0 },
    { question: "A enemigo que huye...", options: ["Puente de plata", "Déjalo ir", "No se sigue", "Se ignora"], answer: 0 },
    { question: "Quien mucho habla...", options: ["Mucho yerra", "Poco hace", "Todo dice", "Ríe más"], answer: 0 },
    { question: "Donde manda capitán...", options: ["No manda marinero", "No hay descanso", "Todo se cumple", "Hay orden"], answer: 0 },
    { question: "Lo prometido...", options: ["Es deuda", "Se cumple", "Vale oro", "Tiene fecha"], answer: 0 },
    { question: "No hay rosa...", options: ["Sin espinas", "Sin perfume", "Sin belleza", "Sin sol"], answer: 0 },
    { question: "Perro viejo...", options: ["No aprende trucos nuevos", "Ladra menos", "Tiene sabiduría", "Se sienta solo"], answer: 0 },
    { question: "Quien espera...", options: ["Desespera", "Recibe", "Pierde tiempo", "Se aburre"], answer: 0 },
    { question: "El que busca...", options: ["Encuentra", "Sufre", "Persiste", "Grita"], answer: 0 },
    { question: "Donde hay humo...", options: ["Hay fuego", "Hay algo", "Hay calor", "Hay misterio"], answer: 0 },
    { question: "La curiosidad mató...", options: ["Al gato", "La sorpresa", "El día", "El misterio"], answer: 0 },
    { question: "No hay camino...", options: ["Se hace al andar", "Sin destino", "Sin piedras", "Sin guía"], answer: 0 },
    { question: "Zapatero...", options: ["A tus zapatos", "A remendar", "Al trabajo", "A la moda"], answer: 0 },
    { question: "El pez por la boca...", options: ["Muere", "Come", "Habla", "Se hunde"], answer: 0 }
  ]
};

const deportes = [
  { question: "¿Cuántos jugadores tiene un equipo de fútbol en el campo?", options: ["11", "10", "12", "9"], answer: 0 },
  { question: "¿En qué deporte se utiliza un 'smash'?", options: ["Bádminton", "Tenis", "Voleibol", "Ping pong"], answer: 0 },
  { question: "¿Quién tiene más títulos de Grand Slam en tenis masculino?", options: ["Rafael Nadal", "Roger Federer", "Novak Djokovic", "Pete Sampras"], answer: 2 },
  { question: "¿En qué país se originó el rugby?", options: ["Inglaterra", "Australia", "Sudáfrica", "Nueva Zelanda"], answer: 0 },
  { question: "¿Cuánto dura un partido de baloncesto NBA?", options: ["48 minutos", "60 minutos", "40 minutos", "30 minutos"], answer: 0 },
  { question: "¿Qué deporte utiliza un disco llamado 'puck'?", options: ["Hockey sobre hielo", "Hockey sobre césped", "Curling", "Lacrosse"], answer: 0 },
  { question: "¿Quién es conocido como 'El Rey del Fútbol'?", options: ["Pelé", "Maradona", "Messi", "Cristiano Ronaldo"], answer: 0 },
  { question: "¿Cuál es la distancia oficial de un maratón?", options: ["42.195 km", "40 km", "50 km", "38 km"], answer: 0 },
  { question: "¿En qué deporte se utiliza una 'katana'?", options: ["Kendo", "Esgrima", "Taekwondo", "Judo"], answer: 0 },
  { question: "¿Quién tiene el récord mundial de 100 metros planos?", options: ["Usain Bolt", "Carl Lewis", "Justin Gatlin", "Tyson Gay"], answer: 0 },
  { question: "¿En qué año se celebraron los primeros Juegos Olímpicos modernos?", options: ["1896", "1900", "1888", "1924"], answer: 0 },
  { question: "¿Qué país ganó la Copa Mundial de Fútbol de 2018?", options: ["Francia", "Croacia", "Brasil", "Alemania"], answer: 0 },
  { question: "¿Cuál es el deporte nacional de Japón?", options: ["Sumo", "Kendo", "Judo", "Karate"], answer: 0 },
  { question: "¿En qué deporte se utiliza un balón ovalado?", options: ["Rugby", "Balonmano", "Fútbol americano", "Ambos Rugby y Fútbol americano"], answer: 3 },
  { question: "¿Qué deporte practica Michael Jordan?", options: ["Baloncesto", "Fútbol", "Golf", "Tenis"], answer: 0 },
  { question: "¿Qué equipo ganó más títulos en la NBA?", options: ["Boston Celtics", "Los Angeles Lakers", "Chicago Bulls", "Golden State Warriors"], answer: 0 },
  { question: "¿Qué significa 'KO' en boxeo?", options: ["Knockout", "Kicking Out", "Keep Off", "King Of"], answer: 0 },
  { question: "¿Cuántos jugadores tiene un equipo de voleibol en cancha?", options: ["6", "7", "5", "4"], answer: 0 },
  { question: "¿Quién es el máximo goleador histórico del fútbol?", options: ["Cristiano Ronaldo", "Pelé", "Lionel Messi", "Romário"], answer: 0 },
  { question: "¿En qué deporte se compite en el Tour de Francia?", options: ["Ciclismo", "Maratón", "Automovilismo", "Natación"], answer: 0 },
  { question: "¿Qué país ganó la Copa América 2021?", options: ["Argentina", "Brasil", "Chile", "Uruguay"], answer: 0 },
  { question: "¿Quién es conocido como 'La Pulga'?", options: ["Lionel Messi", "Neymar", "Luis Suárez", "Cristiano Ronaldo"], answer: 0 },
  { question: "¿Qué deporte se practica en Wimbledon?", options: ["Tenis", "Golf", "Badminton", "Cricket"], answer: 0 },
  { question: "¿Qué es un 'hat-trick' en fútbol?", options: ["Tres goles en un partido", "Tres tarjetas amarillas", "Tres asistencias", "Tres penales fallados"], answer: 0 },
  { question: "¿En qué deporte se utiliza el término 'birdie'?", options: ["Golf", "Tenis", "Cricket", "Bádminton"], answer: 0 },
  { question: "¿Quién es el atleta con más medallas olímpicas?", options: ["Michael Phelps", "Usain Bolt", "Larisa Latynina", "Mark Spitz"], answer: 0 },
  { question: "¿Qué deporte utiliza la palabra 'spike'?", options: ["Voleibol", "Baloncesto", "Fútbol", "Tenis"], answer: 0 },
  { question: "¿Cuántos minutos dura un tiempo en fútbol profesional?", options: ["45 minutos", "30 minutos", "60 minutos", "90 minutos"], answer: 0 },
  { question: "¿Quién ganó el Mundial de Fútbol de 2014?", options: ["Alemania", "Argentina", "Brasil", "España"], answer: 0 },
  { question: "¿Qué deporte utiliza un guante y un bate?", options: ["Béisbol", "Cricket", "Golf", "Hockey"], answer: 0 },
  { question: "¿Qué país tiene más títulos en la NBA?", options: ["Estados Unidos", "España", "Argentina", "Italia"], answer: 0 },
  { question: "¿En qué deporte se usa un tablero llamado 'diana'?", options: ["Dardos", "Billar", "Tenis de mesa", "Bolos"], answer: 0 },
  { question: "¿Quién es conocido como 'La Mano de Dios'?", options: ["Diego Maradona", "Pelé", "Lionel Messi", "Cristiano Ronaldo"], answer: 0 },
  { question: "¿Qué significa 'ace' en tenis?", options: ["Servicio directo sin que el rival toque la pelota", "Golpe fuerte", "Punto ganado en dobles", "Error del rival"], answer: 0 },
  { question: "¿Cuál es el estadio más grande del mundo?", options: ["Rungrado May Day Stadium", "Estadio Azteca", "Wembley", "Maracaná"], answer: 0 },
  { question: "¿Qué país inventó el fútbol?", options: ["Inglaterra", "Brasil", "Italia", "España"], answer: 0 },
  { question: "¿Quién ganó más medallas en natación en los Juegos Olímpicos?", options: ["Michael Phelps", "Mark Spitz", "Katie Ledecky", "Ryan Lochte"], answer: 0 },
  { question: "¿Qué significa 'slam dunk'?", options: ["Mate en baloncesto", "Gol en fútbol", "Punto en tenis", "Golpe en boxeo"], answer: 0 },
  { question: "¿Cuántos jugadores forman un equipo de hockey sobre hielo?", options: ["6", "5", "7", "11"], answer: 0 },
  { question: "¿Cuál es el principal torneo de tenis sobre césped?", options: ["Wimbledon", "Roland Garros", "US Open", "Australian Open"], answer: 0 },
  { question: "¿Qué país ganó más medallas en los Juegos Olímpicos de Tokio 2020?", options: ["Estados Unidos", "China", "Japón", "Rusia"], answer: 0 },
  { question: "¿Qué significa VAR en fútbol?", options: ["Video Assistant Referee", "Valoración Arbitraria de Resultado", "Video Análisis de Reglas", "Verificación Automática de Resultado"], answer: 0 },
  { question: "¿Cuál es la duración de un asalto en boxeo profesional?", options: ["3 minutos", "5 minutos", "2 minutos", "4 minutos"], answer: 0 },
  { question: "¿Qué es un 'touchdown'?", options: ["Anotación en fútbol americano", "Gol en rugby", "Punto en baloncesto", "Gol en fútbol"], answer: 0 },
  { question: "¿Quién ganó el Tour de Francia 2020?", options: ["Tadej Pogačar", "Chris Froome", "Geraint Thomas", "Egan Bernal"], answer: 0 },
  { question: "¿En qué deporte se usa un 'palo de golf'?", options: ["Golf", "Hockey", "Béisbol", "Cricket"], answer: 0 },
  { question: "¿Qué país es conocido por su éxito en el curling?", options: ["Canadá", "Noruega", "Suiza", "Suecia"], answer: 0 },
  { question: "¿Quién es considerado el mejor futbolista argentino?", options: ["Lionel Messi", "Diego Maradona", "Gabriel Batistuta", "Juan Román Riquelme"], answer: 0 },
  { question: "¿Qué deporte se juega en el Estadio Maracaná?", options: ["Fútbol", "Rugby", "Atletismo", "Cricket"], answer: 0 }
];
const tecnologiaMovilesOrdenadores = [
  { question: "¿Qué sistema operativo es más usado en smartphones?", options: ["Android", "iOS", "Windows Phone", "BlackBerry OS"], answer: 0 },
  { question: "¿Quién es el creador del sistema operativo Windows?", options: ["Bill Gates", "Steve Jobs", "Linus Torvalds", "Mark Zuckerberg"], answer: 0 },
  { question: "¿Qué significa CPU?", options: ["Unidad Central de Procesamiento", "Unidad de Control de Programa", "Unidad de Cálculo Primario", "Unidad de Comunicación Personal"], answer: 0 },
  { question: "¿Cuál es la función principal de la RAM en un ordenador?", options: ["Almacenar datos temporales", "Almacenar datos permanentes", "Procesar gráficos", "Conectar a internet"], answer: 0 },
  { question: "¿Qué empresa desarrolló el procesador Intel Core?", options: ["Intel", "AMD", "NVIDIA", "Qualcomm"], answer: 0 },
  { question: "¿Qué puerto es común para conectar dispositivos USB?", options: ["USB-A", "HDMI", "Ethernet", "VGA"], answer: 0 },
  { question: "¿Qué significa 'Android'?", options: ["Sistema operativo móvil de Google", "Una marca de smartphone", "Un tipo de procesador", "Un software antivirus"], answer: 0 },
  { question: "¿Qué tipo de pantalla tienen la mayoría de los smartphones modernos?", options: ["Pantalla táctil", "Pantalla LCD básica", "Pantalla de tinta electrónica", "Pantalla CRT"], answer: 0 },
  { question: "¿Qué es el almacenamiento SSD?", options: ["Unidad de estado sólido", "Disco duro mecánico", "Memoria RAM", "Tarjeta gráfica"], answer: 0 },
  { question: "¿Qué lenguaje de programación es básico para aplicaciones Android?", options: ["Java", "Swift", "Python", "C#"], answer: 0 },
  { question: "¿Qué significa 'Wi-Fi'?", options: ["Wireless Fidelity", "Wide Frequency", "Wireless Fiber", "Wide Fidelity"], answer: 0 },
  { question: "¿Cuál es el sistema operativo de Apple para ordenadores?", options: ["macOS", "Windows", "Linux", "iOS"], answer: 0 },
  { question: "¿Qué es un 'firmware'?", options: ["Software básico integrado en hardware", "Aplicación móvil", "Antivirus", "Sistema operativo"], answer: 0 },
  { question: "¿Qué significa 'GPU'?", options: ["Unidad de Procesamiento Gráfico", "Unidad de Procesamiento General", "Unidad de Almacenamiento", "Unidad de Memoria"], answer: 0 },
  { question: "¿Qué es la pantalla OLED?", options: ["Pantalla con diodos orgánicos emisores de luz", "Pantalla de cristal líquido", "Pantalla de tinta electrónica", "Pantalla CRT"], answer: 0 },
  { question: "¿Qué compañía fabrica los procesadores Snapdragon?", options: ["Qualcomm", "Intel", "AMD", "NVIDIA"], answer: 0 },
  { question: "¿Qué es la resolución en una pantalla?", options: ["Cantidad de píxeles que muestra", "Tamaño de la pantalla", "Brillo máximo", "Consumo de energía"], answer: 0 },
  { question: "¿Qué tipo de memoria almacena el sistema operativo en un PC?", options: ["Disco duro o SSD", "RAM", "Cache", "ROM"], answer: 0 },
  { question: "¿Qué significa 'Bluetooth'?", options: ["Tecnología para conexión inalámbrica de corto alcance", "Un sistema operativo", "Un tipo de procesador", "Una aplicación de mensajería"], answer: 0 },
  { question: "¿Qué es una aplicación 'app'?", options: ["Programa o software para dispositivos móviles", "Hardware", "Conexión a internet", "Tarjeta gráfica"], answer: 0 },
  { question: "¿Cuál es el sistema operativo Linux más popular para usuarios?", options: ["Ubuntu", "Fedora", "Debian", "Arch Linux"], answer: 0 },
  { question: "¿Qué significa 'HTTP'?", options: ["Protocolo de transferencia de hipertexto", "Lenguaje de programación", "Hardware de red", "Sistema operativo"], answer: 0 },
  { question: "¿Qué es una dirección IP?", options: ["Identificador único de un dispositivo en red", "Programa de computadora", "Tipo de hardware", "Sistema operativo"], answer: 0 },
  { question: "¿Qué empresa desarrolló el navegador Chrome?", options: ["Google", "Microsoft", "Mozilla", "Apple"], answer: 0 },
  { question: "¿Qué componente es responsable de almacenar datos a largo plazo?", options: ["Disco duro o SSD", "RAM", "CPU", "GPU"], answer: 0 },
  { question: "¿Qué es la 'nube' en informática?", options: ["Servicios y almacenamiento en internet", "Un tipo de hardware", "Un virus", "Un programa"], answer: 0 },
  { question: "¿Qué es un malware?", options: ["Software malicioso", "Un sistema operativo", "Un programa antivirus", "Un tipo de hardware"], answer: 0 },
  { question: "¿Qué significa 'USB-C'?", options: ["Tipo de conector USB reversible", "Un programa de software", "Una red inalámbrica", "Un tipo de pantalla"], answer: 0 },
  { question: "¿Qué es el overclocking?", options: ["Aumentar la velocidad del procesador más allá de la especificada", "Reducir el consumo de energía", "Actualizar software", "Eliminar virus"], answer: 0 },
  { question: "¿Qué sistema operativo usa la mayoría de los servidores web?", options: ["Linux", "Windows", "macOS", "Android"], answer: 0 },
  { question: "¿Qué significa 'SSD' comparado con HDD?", options: ["Unidad de estado sólido, más rápida que HDD", "Disco duro mecánico", "Memoria RAM", "Tarjeta gráfica"], answer: 0 },
  { question: "¿Qué es un firewall?", options: ["Sistema de seguridad para controlar tráfico de red", "Programa de edición de fotos", "Antivirus", "Sistema operativo"], answer: 0 },
  { question: "¿Qué es la resolución 4K?", options: ["Resolución de pantalla de aproximadamente 3840x2160 píxeles", "Tipo de procesador", "Memoria RAM", "Tipo de conexión"], answer: 0 },
  { question: "¿Qué es una 'tablet'?", options: ["Dispositivo móvil con pantalla táctil", "Tipo de ordenador de escritorio", "Una consola de videojuegos", "Un periférico"], answer: 0 },
  { question: "¿Qué significa 'GHz' en procesadores?", options: ["Gigahercios, frecuencia del procesador", "Cantidad de memoria", "Tipo de pantalla", "Velocidad de disco duro"], answer: 0 },
  { question: "¿Qué es un 'driver' en informática?", options: ["Software que controla un dispositivo hardware", "Sistema operativo", "Aplicación móvil", "Un virus"], answer: 0 },
  { question: "¿Qué es un phishing?", options: ["Intento de robo de datos mediante engaños", "Software antivirus", "Tipo de hardware", "Conexión de red"], answer: 0 },
  { question: "¿Qué es el USB 3.0?", options: ["Versión del estándar USB con mayor velocidad", "Tipo de conexión de pantalla", "Sistema operativo", "Memoria RAM"], answer: 0 },
  { question: "¿Qué empresa creó el iPhone?", options: ["Apple", "Samsung", "Google", "Microsoft"], answer: 0 },
  { question: "¿Qué es un sistema operativo?", options: ["Software que gestiona el hardware y software del ordenador", "Un programa de oficina", "Un hardware", "Un navegador web"], answer: 0 },
  { question: "¿Qué es la nube híbrida?", options: ["Combinación de nube pública y privada", "Un tipo de hardware", "Un software antivirus", "Una red Wi-Fi"], answer: 0 },
  { question: "¿Qué es la realidad aumentada?", options: ["Tecnología que superpone información digital al mundo real", "Una consola de videojuegos", "Un sistema operativo", "Un tipo de memoria"], answer: 0 },
  { question: "¿Qué es la memoria caché?", options: ["Memoria rápida para acceso frecuente", "Memoria de almacenamiento masivo", "RAM estándar", "Disco duro"], answer: 0 },
  { question: "¿Qué es un sistema de archivos?", options: ["Método para organizar datos en almacenamiento", "Programa de edición", "Navegador web", "Software antivirus"], answer: 0 },
  { question: "¿Qué es el Bluetooth 5.0?", options: ["Versión avanzada de tecnología inalámbrica", "Tipo de hardware", "Sistema operativo", "Conexión USB"], answer: 0 },
  { question: "¿Qué es la virtualización?", options: ["Creación de entornos virtuales dentro de un hardware físico", "Un juego de ordenador", "Un programa antivirus", "Un tipo de hardware"], answer: 0 },
  { question: "¿Qué empresa creó el sistema operativo Linux?", options: ["Linus Torvalds", "Bill Gates", "Steve Jobs", "Mark Zuckerberg"], answer: 0 },
  { question: "¿Qué significa 'HTML'?", options: ["Lenguaje de marcado para páginas web", "Sistema operativo", "Programa antivirus", "Tipo de hardware"], answer: 0 },
  { question: "¿Qué es un 'bug' en informática?", options: ["Error o fallo en software", "Hardware", "Virus", "Conexión de red"], answer: 0 },
  { question: "¿Qué es un puerto HDMI?", options: ["Conector para transmitir video y audio digital", "Tipo de conexión de red", "Conector USB", "Pantalla"], answer: 0 },
  { question: "¿Qué es un 'backup'?", options: ["Copia de seguridad de datos", "Un programa antivirus", "Tipo de hardware", "Sistema operativo"], answer: 0 }
];
const depresion = [
  { question: "¿Qué es la depresión?", options: ["Un trastorno del estado de ánimo", "Una enfermedad contagiosa", "Un tipo de alergia", "Un problema digestivo"], answer: 0 },
  { question: "¿Cuál es un síntoma común de la depresión?", options: ["Tristeza persistente", "Fiebre alta", "Dolor de cabeza", "Pérdida de apetito"], answer: 0 },
  { question: "¿Qué puede causar depresión?", options: ["Estrés prolongado", "Solo genética", "Falta de ejercicio", "Comer mucho"], answer: 0 },
  { question: "¿La depresión afecta solo al estado de ánimo?", options: ["No, también afecta energía y concentración", "Sí, solo al ánimo", "No afecta nada", "Solo afecta el sueño"], answer: 0 },
  { question: "¿Qué tipo de tratamiento es común para la depresión?", options: ["Terapia psicológica", "Solo medicación", "Dieta estricta", "Ejercicio solo"], answer: 0 },
  { question: "¿Qué es el 'agotamiento emocional' causado por otras personas?", options: ["Sentirse drenado por relaciones tóxicas", "Una enfermedad viral", "Un tipo de ejercicio", "Un estado de felicidad"], answer: 0 },
  { question: "¿Cómo se llama la sensación de estar sin energía por otras personas?", options: ["Fatiga emocional", "Insomnio", "Ansiedad", "Depresión"], answer: 0 },
  { question: "¿Qué tipo de personas pueden agotar tu energía?", options: ["Personas negativas o tóxicas", "Solo desconocidos", "Animales", "Solo familiares"], answer: 0 },
  { question: "¿Qué puede ayudar a proteger tu energía?", options: ["Establecer límites claros", "Ignorar todo", "Dejar de hablar con todos", "Comer más"], answer: 0 },
  { question: "¿La depresión puede afectar el sueño?", options: ["Sí, puede causar insomnio o hipersomnia", "No", "Solo causa sueño normal", "No afecta para nada"], answer: 0 },
  { question: "¿Qué neurotransmisor está vinculado con la depresión?", options: ["Serotonina", "Adrenalina", "Dopamina", "Melatonina"], answer: 0 },
  { question: "¿La depresión es una señal de debilidad?", options: ["No, es una enfermedad real", "Sí", "Solo en adultos", "No existe"], answer: 0 },
  { question: "¿Qué es la 'fatiga crónica emocional'?", options: ["Cansancio prolongado por estrés y emociones", "Falta de ejercicio", "Una alergia", "Dolor físico"], answer: 0 },
  { question: "¿Puede la depresión causar dificultad para concentrarse?", options: ["Sí", "No", "Solo en niños", "Solo en ancianos"], answer: 0 },
  { question: "¿Qué hacer si alguien te agota emocionalmente?", options: ["Hablar y poner límites", "Evitar contacto sin explicación", "Ignorar para siempre", "Enfadarse mucho"], answer: 0 },
  { question: "¿El ejercicio puede ayudar contra la depresión?", options: ["Sí, libera endorfinas", "No", "Solo con medicación", "No está probado"], answer: 0 },
  { question: "¿La depresión afecta el apetito?", options: ["Puede aumentar o disminuir", "Solo aumenta", "Solo disminuye", "No afecta"], answer: 0 },
  { question: "¿Qué es una persona tóxica?", options: ["Alguien que provoca estrés y agotamiento emocional", "Una persona enferma", "Un buen amigo", "Un desconocido"], answer: 0 },
  { question: "¿Por qué es importante cuidar tu energía emocional?", options: ["Para mantener salud mental y bienestar", "Para ser popular", "Para ganar dinero", "Para dormir mejor"], answer: 0 },
  { question: "¿Qué es el autocuidado emocional?", options: ["Cuidar tu bienestar mental y emocional", "Cuidar solo el cuerpo", "Ignorar problemas", "Ser egoísta"], answer: 0 },
  { question: "¿Qué efecto tiene la depresión en la motivación?", options: ["La disminuye", "La aumenta", "No afecta", "Solo afecta en niños"], answer: 0 },
  { question: "¿Puede la depresión afectar las relaciones personales?", options: ["Sí, puede causar aislamiento", "No", "Solo afecta al trabajo", "Solo afecta a los amigos"], answer: 0 },
  { question: "¿Qué es el estrés emocional?", options: ["Respuesta física y mental a situaciones difíciles", "Una enfermedad física", "Una alergia", "Una dieta"], answer: 0 },
  { question: "¿Qué puede causar agotamiento emocional?", options: ["Conflictos, estrés prolongado y personas tóxicas", "Solo ejercicio físico", "Falta de sueño", "Vacaciones"], answer: 0 },
  { question: "¿La depresión puede ser diagnosticada por un profesional?", options: ["Sí, por psicólogos o psiquiatras", "No", "Solo por amigos", "Solo en hospitales"], answer: 0 },
  { question: "¿Cuál es un síntoma menos conocido de la depresión?", options: ["Dolores físicos inexplicables", "Solo tristeza", "Ganas de bailar", "Aumento de energía"], answer: 0 },
  { question: "¿Qué es el síndrome de burnout?", options: ["Agotamiento emocional por trabajo o estrés", "Una enfermedad contagiosa", "Un tipo de ejercicio", "Una dieta"], answer: 0 },
  { question: "¿Cómo afecta la depresión a la autoestima?", options: ["La disminuye", "La mejora", "No afecta", "Solo afecta a niños"], answer: 0 },
  { question: "¿Qué es la resiliencia emocional?", options: ["Capacidad de recuperarse de adversidades", "Una enfermedad", "Un medicamento", "Un tipo de ejercicio"], answer: 0 },
  { question: "¿Qué papel tiene la terapia en la depresión?", options: ["Ayuda a manejar síntomas y emociones", "No sirve para nada", "Solo es para niños", "Es obligatoria"], answer: 0 },
  { question: "¿Qué son los pensamientos negativos en depresión?", options: ["Ideas que afectan el estado de ánimo y autoestima", "Ideas positivas", "No existen", "Solo ocurren en sueños"], answer: 0 },
  { question: "¿Qué efecto tiene la exposición a personas negativas?", options: ["Puede aumentar el agotamiento emocional", "No tiene efecto", "Solo afecta físicamente", "Solo afecta a otros"], answer: 0 },
  { question: "¿Cuál es una buena práctica para cuidar la energía?", options: ["Tomar descansos y evitar conflictos innecesarios", "Trabajar sin parar", "Ignorar sentimientos", "Evitar amigos"], answer: 0 },
  { question: "¿Qué es la anhedonia?", options: ["Pérdida de interés o placer en actividades", "Alegría extrema", "Cansancio físico", "Un medicamento"], answer: 0 },
  { question: "¿Cómo puede afectar la depresión al sueño?", options: ["Insomnio o dormir demasiado", "Solo insomnio", "Solo dormir mucho", "No afecta"], answer: 0 },
  { question: "¿Qué ayuda a recuperar la energía emocional?", options: ["Tiempo para uno mismo y actividades positivas", "Ignorar problemas", "Estar siempre ocupado", "Evitar contacto con todos"], answer: 0 },
  { question: "¿Qué es un 'vampiro emocional'?", options: ["Persona que drena la energía emocional de otros", "Un mito", "Un tipo de insecto", "Un personaje de ficción"], answer: 0 },
  { question: "¿Puede la meditación ayudar contra la depresión?", options: ["Sí, mejora la salud mental", "No", "Solo en niños", "No está comprobado"], answer: 0 },
  { question: "¿Qué es el apoyo social en depresión?", options: ["Red de personas que ofrecen ayuda emocional", "No sirve de nada", "Solo familia", "Solo amigos"], answer: 0 },
  { question: "¿Por qué es importante identificar personas que agotan tu energía?", options: ["Para proteger tu salud mental", "Para evitar a todos", "Para ser antipático", "No es importante"], answer: 0 },
  { question: "¿Qué es la fatiga emocional?", options: ["Cansancio mental por estrés y emociones", "Cansancio físico", "Un tipo de enfermedad", "Un medicamento"], answer: 0 },
  { question: "¿Qué efecto tiene la música en la depresión?", options: ["Puede mejorar el estado de ánimo", "No tiene efecto", "Siempre empeora", "Solo sirve para dormir"], answer: 0 },
  { question: "¿Qué es la autoempatía?", options: ["Ser comprensivo con uno mismo", "Sentir pena de otros", "Ignorar problemas", "Ser egoísta"], answer: 0 },
  { question: "¿Cómo puede afectar el aislamiento social?", options: ["Puede empeorar la depresión", "No afecta", "Siempre mejora", "Solo afecta físicamente"], answer: 0 },
  { question: "¿Qué significa 'mindfulness'?", options: ["Atención plena al momento presente", "Estar distraído", "Pensar en el pasado", "Dormir mucho"], answer: 0 },
  { question: "¿Qué efecto tiene el ejercicio regular en la depresión?", options: ["Reduce síntomas y mejora energía", "No ayuda", "Solo en niños", "Solo con medicación"], answer: 0 }
];
const decoracion = [
  { question: "¿Cuál es el estilo de decoración que utiliza líneas limpias y colores neutros?", options: ["Minimalista", "Barroco", "Victorian", "Industrial"], answer: 0 },
  { question: "¿Qué tipo de planta es común en la decoración de interiores por su bajo mantenimiento?", options: ["Suculenta", "Orquídea", "Bonsái", "Helecho"], answer: 0 },
  { question: "¿Qué material es típico en el estilo industrial?", options: ["Metal", "Madera tallada", "Terciopelo", "Cerámica"], answer: 0 },
  { question: "¿Qué color se considera neutro y se usa para ampliar espacios visualmente?", options: ["Blanco", "Rojo", "Amarillo", "Negro"], answer: 0 },
  { question: "¿Qué tipo de iluminación crea un ambiente cálido y acogedor?", options: ["Luz cálida", "Luz fría", "Luz azul", "Luz fluorescente"], answer: 0 },
  { question: "¿Qué elemento es clave en la decoración escandinava?", options: ["Madera clara", "Colores oscuros", "Estampados florales", "Cristales"], answer: 0 },
  { question: "¿Qué tipo de textura aporta calidez a un espacio?", options: ["Textiles suaves", "Superficies metálicas", "Paredes lisas", "Vidrio"], answer: 0 },
  { question: "¿Cuál es un accesorio común para decorar mesas de centro?", options: ["Jarrones", "Televisores", "Cojines", "Espejos"], answer: 0 },
  { question: "¿Qué estilo de decoración usa muchos colores y estampados étnicos?", options: ["Bohemio", "Minimalista", "Moderno", "Clásico"], answer: 0 },
  { question: "¿Qué es un 'mood board' en decoración?", options: ["Un collage de ideas y materiales", "Un tipo de mueble", "Una planta", "Un color específico"], answer: 0 },
  { question: "¿Qué elemento ayuda a reflejar la luz y hacer un espacio más luminoso?", options: ["Espejos", "Paredes oscuras", "Cortinas gruesas", "Alfombras"], answer: 0 },
  { question: "¿Qué tipo de cortinas permiten más entrada de luz?", options: ["Visillos", "Blackout", "Opacas", "Gruesas"], answer: 0 },
  { question: "¿Cuál es un mueble típico en un salón?", options: ["Sofá", "Cama", "Escritorio", "Armario"], answer: 0 },
  { question: "¿Qué material es común para muebles de exterior?", options: ["Ratán", "Terciopelo", "Cuero", "Mármol"], answer: 0 },
  { question: "¿Qué estilo de decoración es conocido por sus detalles dorados y ornamentados?", options: ["Barroco", "Minimalista", "Industrial", "Escandinavo"], answer: 0 },
  { question: "¿Qué planta es popular para purificar el aire interior?", options: ["Sansevieria", "Cactus", "Rosa", "Lirio"], answer: 0 },
  { question: "¿Qué elemento se usa para separar espacios sin cerrar habitaciones?", options: ["Biombos", "Paredes", "Puertas", "Ventanas"], answer: 0 },
  { question: "¿Qué tipo de suelo es común en decoración moderna?", options: ["Parquet", "Alfombra shaggy", "Moqueta", "Baldosas hidráulicas"], answer: 0 },
  { question: "¿Qué color transmite tranquilidad y se usa en dormitorios?", options: ["Azul", "Rojo", "Naranja", "Amarillo"], answer: 0 },
  { question: "¿Qué accesorio se usa para decorar paredes?", options: ["Cuadros", "Alfombras", "Lámparas de pie", "Cojines"], answer: 0 },
  { question: "¿Qué es un 'open concept' en diseño de interiores?", options: ["Espacios abiertos y conectados", "Habitaciones separadas", "Decoración clásica", "Estilo rústico"], answer: 0 },
  { question: "¿Qué tipo de iluminación se usa para destacar objetos específicos?", options: ["Focos dirigidos", "Luz ambiental", "Luz difusa", "Luz natural"], answer: 0 },
  { question: "¿Qué es un mueble multifuncional?", options: ["Un mueble con varias funciones", "Un mueble pequeño", "Un mueble antiguo", "Un mueble decorativo"], answer: 0 },
  { question: "¿Cuál es una característica del estilo rústico?", options: ["Uso de madera natural y elementos naturales", "Colores neón", "Diseños futuristas", "Superficies metálicas"], answer: 0 },
  { question: "¿Qué accesorio es común en baños para decoración y funcionalidad?", options: ["Toalleros", "Sofás", "Camas", "Alfombras"], answer: 0 },
  { question: "¿Qué tipo de iluminación es la más saludable para la vista?", options: ["Luz natural", "Luz fluorescente", "Luz azul", "Luz negra"], answer: 0 },
  { question: "¿Qué es un color 'pastel'?", options: ["Color suave y claro", "Color oscuro", "Color brillante", "Color metálico"], answer: 0 },
  { question: "¿Qué tipo de alfombra es buena para espacios pequeños?", options: ["Alfombra clara y pequeña", "Alfombra grande y oscura", "Alfombra gruesa", "Alfombra shaggy"], answer: 0 },
  { question: "¿Qué elemento es típico en la decoración vintage?", options: ["Muebles antiguos restaurados", "Tecnología moderna", "Plantas artificiales", "Vidrios rotos"], answer: 0 },
  { question: "¿Qué es el Feng Shui en decoración?", options: ["Arte de armonizar espacios", "Estilo barroco", "Tipo de pintura", "Un color"], answer: 0 },
  { question: "¿Qué mueble se usa para almacenar ropa?", options: ["Armario", "Silla", "Mesa", "Sofá"], answer: 0 },
  { question: "¿Qué es un cojín decorativo?", options: ["Almohada pequeña para decoración", "Una silla", "Un tipo de planta", "Un cuadro"], answer: 0 },
  { question: "¿Qué estilo usa muebles bajos y líneas rectas?", options: ["Moderno", "Clásico", "Rústico", "Barroco"], answer: 0 },
  { question: "¿Qué tipo de tela es común para cortinas elegantes?", options: ["Seda", "Lona", "Algodón", "Nylon"], answer: 0 },
  { question: "¿Qué elemento decorativo se coloca comúnmente en chimeneas?", options: ["Velas", "Libros", "Relojes", "Plantas"], answer: 0 },
  { question: "¿Qué color se asocia con la elegancia y sofisticación?", options: ["Negro", "Amarillo", "Rosa", "Verde"], answer: 0 },
  { question: "¿Qué estilo es popular por su uso de materiales reciclados?", options: ["Eco-friendly", "Industrial", "Minimalista", "Clásico"], answer: 0 },
  { question: "¿Qué elemento aporta textura a las paredes?", options: ["Papel tapiz", "Pintura lisa", "Espejos", "Cristales"], answer: 0 },
  { question: "¿Qué es una lámpara colgante?", options: ["Lámpara suspendida del techo", "Lámpara de mesa", "Foco de pared", "Lámpara de pie"], answer: 0 },
  { question: "¿Qué mueble se usa para sentarse en la sala?", options: ["Sofá", "Cama", "Escritorio", "Armario"], answer: 0 },
  { question: "¿Qué tipo de suelo es común en cocinas modernas?", options: ["Baldosas", "Alfombra", "Madera", "Moqueta"], answer: 0 },
  { question: "¿Qué tipo de pintura es ideal para zonas húmedas?", options: ["Antimoho", "Mate", "Satinada", "Acrílica"], answer: 0 },
  { question: "¿Qué mueble es fundamental en un comedor?", options: ["Mesa de comedor", "Sofá", "Cama", "Estantería"], answer: 0 },
  { question: "¿Qué accesorio se usa para decorar ventanas?", options: ["Cortinas", "Alfombras", "Cuadros", "Lámparas"], answer: 0 },
  { question: "¿Qué tipo de decoración es popular en apartamentos pequeños?", options: ["Minimalista", "Barroco", "Vintage", "Clásico"], answer: 0 },
  { question: "¿Qué estilo de decoración incluye elementos metálicos y ladrillo visto?", options: ["Industrial", "Escandinavo", "Rústico", "Bohemio"], answer: 0 },
  { question: "¿Qué tipo de muebles suelen ser plegables para ahorrar espacio?", options: ["Mesas y sillas plegables", "Sofás fijos", "Camas grandes", "Armarios empotrados"], answer: 0 },
  { question: "¿Qué color suele usarse para dar sensación de mayor altura?", options: ["Blanco", "Negro", "Rojo", "Azul"], answer: 0 },
  { question: "¿Qué tipo de alfombra es mejor para zonas de mucho tránsito?", options: ["Alfombra de pelo corto", "Alfombra de pelo largo", "Alfombra de lana", "Alfombra de seda"], answer: 0 },
];
const decoracion = [
  { question: "¿Cuál es el estilo de decoración que utiliza líneas limpias y colores neutros?", options: ["Minimalista", "Barroco", "Victorian", "Industrial"], answer: 0 },
  { question: "¿Qué tipo de planta es común en la decoración de interiores por su bajo mantenimiento?", options: ["Suculenta", "Orquídea", "Bonsái", "Helecho"], answer: 0 },
  { question: "¿Qué material es típico en el estilo industrial?", options: ["Metal", "Madera tallada", "Terciopelo", "Cerámica"], answer: 0 },
  { question: "¿Qué color se considera neutro y se usa para ampliar espacios visualmente?", options: ["Blanco", "Rojo", "Amarillo", "Negro"], answer: 0 },
  { question: "¿Qué tipo de iluminación crea un ambiente cálido y acogedor?", options: ["Luz cálida", "Luz fría", "Luz azul", "Luz fluorescente"], answer: 0 },
  { question: "¿Qué elemento es clave en la decoración escandinava?", options: ["Madera clara", "Colores oscuros", "Estampados florales", "Cristales"], answer: 0 },
  { question: "¿Qué tipo de textura aporta calidez a un espacio?", options: ["Textiles suaves", "Superficies metálicas", "Paredes lisas", "Vidrio"], answer: 0 },
  { question: "¿Cuál es un accesorio común para decorar mesas de centro?", options: ["Jarrones", "Televisores", "Cojines", "Espejos"], answer: 0 },
  { question: "¿Qué estilo de decoración usa muchos colores y estampados étnicos?", options: ["Bohemio", "Minimalista", "Moderno", "Clásico"], answer: 0 },
  { question: "¿Qué es un 'mood board' en decoración?", options: ["Un collage de ideas y materiales", "Un tipo de mueble", "Una planta", "Un color específico"], answer: 0 },
  { question: "¿Qué elemento ayuda a reflejar la luz y hacer un espacio más luminoso?", options: ["Espejos", "Paredes oscuras", "Cortinas gruesas", "Alfombras"], answer: 0 },
  { question: "¿Qué tipo de cortinas permiten más entrada de luz?", options: ["Visillos", "Blackout", "Opacas", "Gruesas"], answer: 0 },
  { question: "¿Cuál es un mueble típico en un salón?", options: ["Sofá", "Cama", "Escritorio", "Armario"], answer: 0 },
  { question: "¿Qué material es común para muebles de exterior?", options: ["Ratán", "Terciopelo", "Cuero", "Mármol"], answer: 0 },
  { question: "¿Qué estilo de decoración es conocido por sus detalles dorados y ornamentados?", options: ["Barroco", "Minimalista", "Industrial", "Escandinavo"], answer: 0 },
  { question: "¿Qué planta es popular para purificar el aire interior?", options: ["Sansevieria", "Cactus", "Rosa", "Lirio"], answer: 0 },
  { question: "¿Qué elemento se usa para separar espacios sin cerrar habitaciones?", options: ["Biombos", "Paredes", "Puertas", "Ventanas"], answer: 0 },
  { question: "¿Qué tipo de suelo es común en decoración moderna?", options: ["Parquet", "Alfombra shaggy", "Moqueta", "Baldosas hidráulicas"], answer: 0 },
  { question: "¿Qué color transmite tranquilidad y se usa en dormitorios?", options: ["Azul", "Rojo", "Naranja", "Amarillo"], answer: 0 },
  { question: "¿Qué accesorio se usa para decorar paredes?", options: ["Cuadros", "Alfombras", "Lámparas de pie", "Cojines"], answer: 0 },
  { question: "¿Qué es un 'open concept' en diseño de interiores?", options: ["Espacios abiertos y conectados", "Habitaciones separadas", "Decoración clásica", "Estilo rústico"], answer: 0 },
  { question: "¿Qué tipo de iluminación se usa para destacar objetos específicos?", options: ["Focos dirigidos", "Luz ambiental", "Luz difusa", "Luz natural"], answer: 0 },
  { question: "¿Qué es un mueble multifuncional?", options: ["Un mueble con varias funciones", "Un mueble pequeño", "Un mueble antiguo", "Un mueble decorativo"], answer: 0 },
  { question: "¿Cuál es una característica del estilo rústico?", options: ["Uso de madera natural y elementos naturales", "Colores neón", "Diseños futuristas", "Superficies metálicas"], answer: 0 },
  { question: "¿Qué accesorio es común en baños para decoración y funcionalidad?", options: ["Toalleros", "Sofás", "Camas", "Alfombras"], answer: 0 },
  { question: "¿Qué tipo de iluminación es la más saludable para la vista?", options: ["Luz natural", "Luz fluorescente", "Luz azul", "Luz negra"], answer: 0 },
  { question: "¿Qué es un color 'pastel'?", options: ["Color suave y claro", "Color oscuro", "Color brillante", "Color metálico"], answer: 0 },
  { question: "¿Qué tipo de alfombra es buena para espacios pequeños?", options: ["Alfombra clara y pequeña", "Alfombra grande y oscura", "Alfombra gruesa", "Alfombra shaggy"], answer: 0 },
  { question: "¿Qué elemento es típico en la decoración vintage?", options: ["Muebles antiguos restaurados", "Tecnología moderna", "Plantas artificiales", "Vidrios rotos"], answer: 0 },
  { question: "¿Qué es el Feng Shui en decoración?", options: ["Arte de armonizar espacios", "Estilo barroco", "Tipo de pintura", "Un color"], answer: 0 },
  { question: "¿Qué mueble se usa para almacenar ropa?", options: ["Armario", "Silla", "Mesa", "Sofá"], answer: 0 },
  { question: "¿Qué es un cojín decorativo?", options: ["Almohada pequeña para decoración", "Una silla", "Un tipo de planta", "Un cuadro"], answer: 0 },
  { question: "¿Qué estilo usa muebles bajos y líneas rectas?", options: ["Moderno", "Clásico", "Rústico", "Barroco"], answer: 0 },
  { question: "¿Qué tipo de tela es común para cortinas elegantes?", options: ["Seda", "Lona", "Algodón", "Nylon"], answer: 0 },
  { question: "¿Qué elemento decorativo se coloca comúnmente en chimeneas?", options: ["Velas", "Libros", "Relojes", "Plantas"], answer: 0 },
  { question: "¿Qué color se asocia con la elegancia y sofisticación?", options: ["Negro", "Amarillo", "Rosa", "Verde"], answer: 0 },
  { question: "¿Qué estilo es popular por su uso de materiales reciclados?", options: ["Eco-friendly", "Industrial", "Minimalista", "Clásico"], answer: 0 },
  { question: "¿Qué elemento aporta textura a las paredes?", options: ["Papel tapiz", "Pintura lisa", "Espejos", "Cristales"], answer: 0 },
  { question: "¿Qué es una lámpara colgante?", options: ["Lámpara suspendida del techo", "Lámpara de mesa", "Foco de pared", "Lámpara de pie"], answer: 0 },
  { question: "¿Qué mueble se usa para sentarse en la sala?", options: ["Sofá", "Cama", "Escritorio", "Armario"], answer: 0 },
  { question: "¿Qué tipo de suelo es común en cocinas modernas?", options: ["Baldosas", "Alfombra", "Madera", "Moqueta"], answer: 0 },
  { question: "¿Qué tipo de pintura es ideal para zonas húmedas?", options: ["Antimoho", "Mate", "Satinada", "Acrílica"], answer: 0 },
  { question: "¿Qué mueble es fundamental en un comedor?", options: ["Mesa de comedor", "Sofá", "Cama", "Estantería"], answer: 0 },
  { question: "¿Qué accesorio se usa para decorar ventanas?", options: ["Cortinas", "Alfombras", "Cuadros", "Lámparas"], answer: 0 },
  { question: "¿Qué tipo de decoración es popular en apartamentos pequeños?", options: ["Minimalista", "Barroco", "Vintage", "Clásico"], answer: 0 },
  { question: "¿Qué estilo de decoración incluye elementos metálicos y ladrillo visto?", options: ["Industrial", "Escandinavo", "Rústico", "Bohemio"], answer: 0 },
  { question: "¿Qué tipo de muebles suelen ser plegables para ahorrar espacio?", options: ["Mesas y sillas plegables", "Sofás fijos", "Camas grandes", "Armarios empotrados"], answer: 0 },
  { question: "¿Qué color suele usarse para dar sensación de mayor altura?", options: ["Blanco", "Negro", "Rojo", "Azul"], answer: 0 },
  { question: "¿Qué tipo de alfombra es mejor para zonas de mucho tránsito?", options: ["Alfombra de pelo corto", "Alfombra de pelo largo", "Alfombra de lana", "Alfombra de seda"], answer: 0 },
];

  question: "¿Cómo conservar el plátano para que no madure rápido?", 
  options: [
    "Separándolos y envolviéndolos en papel film", 
    "Guardándolos juntos en una bolsa plástica", 
    "Poniéndolos al sol", 
    "Guardándolos en agua fría"
  answer: 0
  ], 
}

   


